# Generated by Django 4.2.20 on 2025-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fraction', models.FloatField(help_text='Fraction of damage taken, e.g., 0.25 for 25% damage taken.')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NPCCharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('halfling', 'Halfling'), ('orc', 'Orc'), ('tiefling', 'Tiefling'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome')], max_length=50)),
                ('alignment', models.CharField(blank=True, choices=[('lg', 'Lawful Good'), ('ng', 'Neutral Good'), ('cg', 'Chaotic Good'), ('ln', 'Lawful Neutral'), ('tn', 'True Neutral'), ('cn', 'Chaotic Neutral'), ('le', 'Lawful Evil'), ('ne', 'Neutral Evil'), ('ce', 'Chaotic Evil')], max_length=50)),
                ('armor_class', models.IntegerField()),
                ('health_points', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('challange_rating', models.FloatField()),
                ('xp_gain', models.IntegerField()),
                ('damage_resistances', models.ManyToManyField(blank=True, related_name='npc_cards_damage_resistances', to='npc_cards.damageresistance')),
                ('senses', models.ManyToManyField(blank=True, related_name='npc_cards_senses', to='npc_cards.sense')),
                ('skills', models.ManyToManyField(blank=True, related_name='npc_cards_skills', to='npc_cards.skill')),
            ],
        ),
    ]
