# Generated by Django 4.2.20 on 2025-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npccharactercard',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
