# Generated by Django 4.2.20 on 2025-05-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, to='npc_cards.item')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='npc_cards.location')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='npccharactercard',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='npc_cards/'),
        ),
        migrations.AlterField(
            model_name='npccharactercard',
            name='race',
            field=models.CharField(blank=True, choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('halfling', 'Halfling'), ('orc', 'Orc'), ('tiefling', 'Tiefling'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome')], default='human', max_length=50),
        ),
        migrations.CreateModel(
            name='NPCInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='NPC', max_length=100)),
                ('character_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npc_instances', to='npc_cards.npccharactercard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_npc', to='npc_cards.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='universe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='npc_cards.universe'),
        ),
    ]
