# Generated by Django 4.2.20 on 2025-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0002_npccharactercard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npccharactercard',
            name='image',
            field=models.ImageField(blank=True, upload_to='npc_cards/'),
        ),
    ]
