# Generated by Django 4.2.20 on 2025-05-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0002_item_location_universe_npccharactercard_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blueprint', models.BooleanField(default=False)),
                ('image_url', models.ImageField(blank=True, upload_to='npc_cards/')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('halfling', 'Halfling'), ('orc', 'Orc'), ('tiefling', 'Tiefling'), ('dragonborn', 'Dragonborn'), ('gnome', 'Gnome')], default='human', max_length=50, null=True)),
                ('alignment', models.CharField(blank=True, choices=[('lg', 'Lawful Good'), ('ng', 'Neutral Good'), ('cg', 'Chaotic Good'), ('ln', 'Lawful Neutral'), ('tn', 'True Neutral'), ('cn', 'Chaotic Neutral'), ('le', 'Lawful Evil'), ('ne', 'Neutral Evil'), ('ce', 'Chaotic Evil')], max_length=50, null=True)),
                ('armor_class', models.IntegerField()),
                ('health_points', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('challange_rating', models.FloatField()),
                ('xp_gain', models.IntegerField()),
                ('blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='npc_cards.npccharacter')),
                ('damage_resistances', models.ManyToManyField(blank=True, related_name='npc_cards_damage_resistances', to='npc_cards.damageresistance')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='npc_cards.location')),
                ('senses', models.ManyToManyField(blank=True, related_name='npc_cards_senses', to='npc_cards.sense')),
                ('skills', models.ManyToManyField(blank=True, related_name='npc_cards_skills', to='npc_cards.skill')),
            ],
        ),
        migrations.RemoveField(
            model_name='npcinstance',
            name='character_card',
        ),
        migrations.RemoveField(
            model_name='npcinstance',
            name='location',
        ),
        migrations.DeleteModel(
            name='NPCCharacterCard',
        ),
        migrations.DeleteModel(
            name='NPCInstance',
        ),
    ]
