# Generated by Django 4.2.20 on 2025-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0003_npccharacter_remove_npcinstance_character_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npccharacter',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
