# Generated by Django 4.2.20 on 2025-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0003_alter_npccharactercard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npccharactercard',
            name='image',
        ),
        migrations.AddField(
            model_name='npccharactercard',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='npc_cards/'),
        ),
    ]
