# Generated by Django 4.2.20 on 2025-05-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0004_remove_npccharactercard_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='npc_cards.location')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NPCInstance',
            fields=[
                ('npccharactercard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='npc_cards.npccharactercard')),
                ('Name', models.CharField(default='NPC', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_npc', to='npc_cards.location')),
            ],
            bases=('npc_cards.npccharactercard',),
        ),
        migrations.AddField(
            model_name='location',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc_cards.universe'),
        ),
    ]
