# Generated by Django 4.2.20 on 2025-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0005_location_creator_npccharacter_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='x_coord',
            field=models.FloatField(blank=True, help_text="X coordinate on parent's map", null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='y_coord',
            field=models.FloatField(blank=True, help_text="Y coordinate on parent's map", null=True),
        ),
    ]
