# Generated by Django 4.2.20 on 2025-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0005_item_location_universe_npcinstance_location_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='npc_cards.item'),
        ),
    ]
