# Generated by Django 4.2.20 on 2025-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0006_location_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='items',
            field=models.ManyToManyField(blank=True, to='npc_cards.item'),
        ),
    ]
