# Generated by Django 4.2.20 on 2025-05-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0007_alter_location_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='universe',
        ),
        migrations.AddField(
            model_name='universe',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='npc_cards.location'),
        ),
    ]
