# Generated by Django 4.2.20 on 2025-05-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_cards', '0008_remove_location_universe_universe_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='universe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='npc_cards.universe'),
        ),
    ]
